### ISSUE TITLE
`noarch: python` repeated

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pipreqs-feedstock#10]
Appears [`noarch: python` is repeated 3 times in this recipe]( https://github.com/conda-forge/pipreqs-feedstock/blob/0f54c19da2bbc6e98d18e494a5336a74dbefbbbc/recipe/meta.yaml#L15-L17 ). Would be good to consolidate this to once.

**Comment by proinsias** [comment]
Addressed in latest version.

**Comment by jakirkham** [comment]
Thanks Francis!
